### PR TITLE
show/hide password functionality added

### PR DESCRIPTION
**Pull request by Siddhesh777**
### What kind of change does this PR introduce ?

It has a functionality which toggles the view of password (show/hide).

### Documentation updated ?

No need

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Code is working on both device and system

### CODE REVIEW

**Review by Drontitan — CHANGES_REQUESTED** [review]
pls properly align the icon in the middle and there in some error in the compilation so pls check your package.json

**Comment by Siddhesh777** [comment]
hey @Drontitan 
Can you check it right now whether icon is alligned or not

**Review by Drontitan — APPROVED** [review]

**Review by Drontitan — CHANGES_REQUESTED** [review]
@Siddhesh777 can pls take that icon inside that password block it will be more fine . Now it outside so it looks like the size of the email and password box didn't match 

when you will do these let me know i will surely approve that😂

**Comment by Siddhesh777** [comment]
okay sure @Drontitan 
I'll do it!

**Comment by Siddhesh777** [comment]
hey @Drontitan 
I had taken the toggle button inside the password field.
Please check it and kindly merge.

**Review by Drontitan — APPROVED** [review]

**Pull request merged**
